name: simple-storage
jobs:
  cases:
    steps:
      - uri: fs/build
        method: deployContract
        args:
          connection:
            networkNameOrChainId: "testnet"
    jobs:
      case1:
        steps:
          - uri: fs/build
            method: setData
            args:
              address: "$cases.0.data"
              value: 100
          - uri: fs/build
            method: getData
            args:
              address: "$cases.0.data"
      case2:
        steps:
          - uri: fs/build
            method: setIpfsData
            args:
              options:
                address: "$cases.0.data"
                data: "Hello from IPFS!"
          - uri: fs/build
            method: getIpfsData
            args:
              address: "$cases.0.data"